// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteLaser(arg1:string):Promise<void>;

export function DeleteMaterial(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExecuteJob(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:main.MaterialProfile,arg7:main.JobOptions):Promise<main.JobExecutionResult>;

export function GetLasers():Promise<Array<main.Laser>>;

export function GetMaterials():Promise<Array<main.MaterialProfile>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function LoadFontDataForFamily(arg1:string):Promise<string>;

export function OpenSVGFile():Promise<main.FileResponse>;

export function SaveLaser(arg1:main.Laser):Promise<void>;

export function SaveMaterial(arg1:main.MaterialProfile):Promise<void>;

export function SaveProfile(arg1:main.Profile):Promise<void>;

export function TestConnection(arg1:string,arg2:number,arg3:string):Promise<boolean>;
