// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLaser(arg1) {
  return window['go']['main']['App']['DeleteLaser'](arg1);
}

export function DeleteMaterial(arg1) {
  return window['go']['main']['App']['DeleteMaterial'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExecuteJob(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExecuteJob'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetLasers() {
  return window['go']['main']['App']['GetLasers']();
}

export function GetMaterials() {
  return window['go']['main']['App']['GetMaterials']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function LoadFontDataForFamily(arg1) {
  return window['go']['main']['App']['LoadFontDataForFamily'](arg1);
}

export function OpenSVGFile() {
  return window['go']['main']['App']['OpenSVGFile']();
}

export function SaveLaser(arg1) {
  return window['go']['main']['App']['SaveLaser'](arg1);
}

export function SaveMaterial(arg1) {
  return window['go']['main']['App']['SaveMaterial'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}
